name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.15.1

      - name: Checkout infra dependency
        run: |
          git clone https://github.com/zig-whatwg/infra.git ../infra || true
        shell: bash

      - name: Run tests
        run: zig build test

      - name: Build executable
        run: zig build

  fmt:
    name: Format check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.15.1

      - name: Check formatting
        run: zig fmt --check src/
